### ISSUE TITLE
你好，egg-rbac 如何支持带参数的url？

### ISSUE THREAD

**Issue by meguoe** [lidianhao123/egg-rbac#2]
app.router.get('/admin/:id', can(), 'home.index');

例如您示例中的路由，增加id后实际访问后URL是/admin/123，这个时候rbac就验证不过去了，请问该插件有解决的办法吗？

**Comment by meguoe** [comment]
我自己解决了，把can()方法中的ctx.request.url 换成ctx.routerPath就好了。

function can() {
  return async function(ctx, next) {
    console.info(ctx.routerPath, ctx.originalUrl);
    if (ctx.role && ctx.role.can && ctx.role.can(ctx.routerPath)) {
      await next();
    } else {
      ctx.body = {
        code: 401,
        msg: 'no permission',
      };
    }
  };
}

**Comment by lidianhao123** [comment]
好的，权限项的判断是直接用 permission 的 name 进行字符串判断的，所以只能字符串全匹配来处理。
